services:
  postgres-b2b:
    image: postgres:16-alpine
    container_name: postgres_b2b
    environment:
      POSTGRES_DB: b2b
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_b2b_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d b2b"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres-moderation:
    image: postgres:16-alpine
    container_name: postgres_moderation
    environment:
      POSTGRES_DB: moderation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_moderation_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moderation"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres-b2c:
    image: postgres:16-alpine
    container_name: postgres_b2c
    environment:
      POSTGRES_DB: b2c
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_b2c_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d b2c"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_b2b_data:
  postgres_moderation_data:
  postgres_b2c_data:
